###########################################
# make.inc 
# 
# settings of local paths to
# libraries (eigen and gdal)
#
# Author: Claas Grohnfeldt
###########################################

# path to EIGEN source/headers (top folder, Eigen headers are called via #include <Eigen/Dense> etc)
EIGEN_HEADER_PATH = ./lib/eigen/eigen-eigen-f562a193118d/

# path to GDAL library
#GDAL_LIBRARY_PATH = /usr/local/lib
GDAL_INCLUDE_PATH = ./lib/gdal/inc
GDAL_LIBRARY_PATH = ./lib/gdal/lib

